services:
  - type: web
    name: motorsports-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app --bind 0.0.0.0:$PORT"
    autoDeploy: true
    branch: main
    region: oregon
    rootDir: .